### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by kbala-ami** [KaanEmec/MaterialTextField#1]
Hi,

I have added the MaterialTextField by code,

let username:UIMaterialTextField = UIMaterialTextField(frame: CGRect(x: 0, y: 0, width: 200, height: 40))
        section2.addSubview(username)
        username.placeholder = "Email or Username"
        username.delegate = self
        username.materialDelegate = self

But the animation not working while entering text, Please help.

**Comment by KaanEmec** [comment]
Hi,

**Comment by kbala-ami** [comment]
Hi, any help?

**Comment by KaanEmec** [comment]
Hi,

Sorry for the delay. Just ommit the "username.delegate = self" line as the
textbox delegate in materialtextfield is controlled by itself.

Animations are handled in textbox delegate functions.

If you need to use delegate events for that textbox, just use
materialtextfielddelegate functions in your viewcontroller.

Hope it helps!

Kaan
