### ISSUE TITLE
Issue when instantiating the text field programmatically

### ISSUE THREAD

**Issue by adamdahan** [KaanEmec/MaterialTextField#3]
Instantiate it programmatically in a view controller and just run the project instant crash on super.placeholder!

your unwrapping it without checking to see if it's nil and it is.

**Comment by adamdahan** [comment]
Also the delegate methods don't get fired when assigning self (my view controller) to .materialDelegate

**Comment by KaanEmec** [comment]
Hi, both issues are resolved with the latest commit.
